---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ex-constant-vars
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
resources:
  repository: https://github.com/neilbowers/ex-constant-vars
version: 0.04
